module.exports = {
	mongoURI: process.env.MONGO_URI,
	googleClientId: process.env.GOOGLE_CLIENT_ID,
	googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
	cookieKey: process.env.COOKIE_KEY,
	DB_MYSQL_USER: process.env.DB_MYSQL_USER,
	DB_MYSQL_PASS: process.env.DB_MYSQL_PASS,
	accessKeyId: process.env.accessKeyId,
	secretAccessKey: process.env.secretAccessKey,
	region: process.env.region,
	ISBN_AUTH_API: process.env.ISBN_AUTH_API,
	GOOGLE_BOOKS_API: process.env.GOOGLE_BOOKS_API,
	REACT_APP_PUBLIC_POSTHOG_KEY: process.env.PUBLIC_POSTHOG_KEY,
	REACT_APP_PUBLIC_POSTHOG_HOST: process.env.PUBLIC_POSTHOG_HOST,
};
